/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ysop7mLf1lK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Gabarito } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col min-h-screen">
      <section className="relative h-screen flex flex-col justify-center items-center bg-[url('/hero-image.jpg')] bg-cover bg-center">
        <div className="absolute inset-0 bg-black/50" />
        <div className="relative z-10 text-center text-white max-w-3xl px-4">
          <h1 className="text-4xl font-bold mb-4 sm:text-6xl">Discover Your Perfect Getaway</h1>
          <p className="text-lg mb-8 sm:text-xl">
            Experience the comfort and charm of our cozy homestay, nestled in the heart of nature.
          </p>
          <Link
            href="#"
            className="inline-flex items-center justify-center px-6 py-3 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            Book Now
          </Link>
        </div>
      </section>
      <section className="py-20 bg-background">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
            <div>
              <img src="/placeholder.svg" width={500} height={500} alt="Host" className="rounded-lg" />
            </div>
            <div>
              <h2 className="text-3xl font-bold mb-4">Meet Your Host</h2>
              <p className="text-muted-foreground mb-6">
                Hi, I'm Sarah, the proud owner of this cozy homestay. I've been hosting guests for over 10 years and I'm
                passionate about providing a warm and welcoming experience for everyone who stays with us.
              </p>
              <p className="text-muted-foreground mb-6">
                Our homestay is a reflection of my love for nature and hospitality. I've carefully curated every detail
                to ensure your stay is comfortable and memorable. I look forward to welcoming you and helping you create
                unforgettable memories.
              </p>
              <Link
                href="#"
                className="inline-flex items-center justify-center px-6 py-3 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                prefetch={false}
              >
                Learn More
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className="py-20 bg-muted">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <h2 className="text-3xl font-bold mb-8 text-center">What Our Guests Say</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <div className="bg-background rounded-lg p-6 shadow-md">
                <div className="flex items-center mb-4">
                  <Avatar className="mr-4">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <h3 className="font-bold">John Doe</h3>
                    <p className="text-muted-foreground">Satisfied Guest</p>
                  </div>
                </div>
                <p className="text-muted-foreground">
                  "Our stay at this cozy homestay was an absolute delight.\n The host, Sarah, was incredibly welcoming
                  and made us feel\n right at home. The attention to detail and the serene\n surroundings made for a
                  truly memorable experience."
                </p>
              </div>
            </div>
            <div>
              <div className="bg-background rounded-lg p-6 shadow-md">
                <div className="flex items-center mb-4">
                  <Avatar className="mr-4">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JA</AvatarFallback>
                  </Avatar>
                  <div>
                    <h3 className="font-bold">Jane Appleseed</h3>
                    <p className="text-muted-foreground">Satisfied Guest</p>
                  </div>
                </div>
                <p className="text-muted-foreground">
                  "I had the most wonderful time at this charming homestay.\n The host, Sarah, went above and beyond to
                  ensure our stay\n was comfortable and enjoyable. The serene natural\n surroundings were the perfect
                  backdrop for a relaxing\n getaway."
                </p>
              </div>
            </div>
          </div>
          <div className="mt-12 text-center">
            <h3 className="text-2xl font-bold mb-4">Video Testimonials</h3>
            <div className="aspect-video rounded-lg overflow-hidden">
              <iframe
                src="https://www.youtube.com/embed/dQw4w9WgXcQ"
                frameBorder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                className="w-full h-full"
              />
            </div>
          </div>
        </div>
      </section>
      <section className="py-20 bg-background">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <h2 className="text-3xl font-bold mb-8 text-center">Explore Our Gallery</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            <Link href="#" className="group relative overflow-hidden rounded-lg" prefetch={false}>
              <img
                src="/placeholder.svg"
                width={500}
                height={500}
                alt="Gallery"
                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <SearchIcon className="w-8 h-8 text-white" />
              </div>
            </Link>
            <Link href="#" className="group relative overflow-hidden rounded-lg" prefetch={false}>
              <img
                src="/placeholder.svg"
                width={500}
                height={500}
                alt="Gallery"
                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <SearchIcon className="w-8 h-8 text-white" />
              </div>
            </Link>
            <Link href="#" className="group relative overflow-hidden rounded-lg" prefetch={false}>
              <img
                src="/placeholder.svg"
                width={500}
                height={500}
                alt="Gallery"
                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <SearchIcon className="w-8 h-8 text-white" />
              </div>
            </Link>
            <Link href="#" className="group relative overflow-hidden rounded-lg" prefetch={false}>
              <img
                src="/placeholder.svg"
                width={500}
                height={500}
                alt="Gallery"
                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <SearchIcon className="w-8 h-8 text-white" />
              </div>
            </Link>
            <Link href="#" className="group relative overflow-hidden rounded-lg" prefetch={false}>
              <img
                src="/placeholder.svg"
                width={500}
                height={500}
                alt="Gallery"
                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <SearchIcon className="w-8 h-8 text-white" />
              </div>
            </Link>
            <Link href="#" className="group relative overflow-hidden rounded-lg" prefetch={false}>
              <img
                src="/placeholder.svg"
                width={500}
                height={500}
                alt="Gallery"
                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <SearchIcon className="w-8 h-8 text-white" />
              </div>
            </Link>
          </div>
        </div>
      </section>
      <section className="py-20 bg-muted">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <h2 className="text-3xl font-bold mb-8 text-center">Get in Touch</h2>
          <div className="max-w-md mx-auto">
            <form>
              <div className="mb-4">
                <label htmlFor="name" className="block text-muted-foreground mb-2">
                  Name
                </label>
                <Input id="name" type="text" placeholder="Enter your name" />
              </div>
              <div className="mb-4">
                <label htmlFor="email" className="block text-muted-foreground mb-2">
                  Email
                </label>
                <Input id="email" type="email" placeholder="Enter your email" />
              </div>
              <div className="mb-4">
                <label htmlFor="message" className="block text-muted-foreground mb-2">
                  Message
                </label>
                <Textarea id="message" rows={5} placeholder="Enter your message" />
              </div>
              <Button
                type="submit"
                className="w-full bg-primary text-primary-foreground hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
              >
                Send Message
              </Button>
            </form>
          </div>
        </div>
      </section>
      <footer className="bg-background py-6 border-t">
        <div className="container mx-auto px-4 md:px-6 lg:px-8 flex justify-between items-center">
          <p className="text-muted-foreground">&copy; 2024 Cozy Homestay. All rights reserved.</p>
          <nav className="flex gap-4">
            <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
              Terms of Service
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
